from pathlib import Path
from PIL import Image

KNOWLEDGE_FILEPATH = Path("wissensquellen")
LOGO_IMG = Image.open('resources/nico_mario.png')
FAVICON = Image.open('resources/favicon.png')
JSONLNAME = "knowledge_jsonl.jsonl"  # Do not change
EXAMPLES_CONTEXT = "Khuska Purispa dient der Unternehmertumsförderung und Empowerment von Frauen. Das Projekt baut auf den Erfolgen eines vergangenen von ALTERNAID ermöglichten Projekts auf: 5.271 Tarabäumen wurden gepflanzt. 183 Familien sind auf dem Wege, sich dank neuer unternehmerischer Tätigkeit ein zusätzliches Einkommen aufzubauen. Doch noch ist die Rollen- und Chancenungleichheit hoch im bolivianischen Hochland. Empowerment von Frauen soll im neuen Projekt auf fundamentaler Ebene adressiert werden, mitunter durch ein Female Leadership Programm. Es werden Evaluierungsmethoden entwickelt, um unsere Wirkung im Zusammenhang mit diesem Kernziel messbarer erfassen – unterstützt durch eine von Ehrenamtlichen eigens entwickelte App. Ein breites und diversifiziertes Angebot an Maßnahmen zur Unternehmertumsförderung wird geschaffen, mit der Zielsetzung insgesamt. Maßnahmen zur Unternehmertumsförderung wird geschaffen, mit der Zielsetzung insgesamt 250 Familien Micanis zu zusätzlichen Einkommensquellen zu verhelfen. Das Projekt wird über einen Zeitraum von 3 Jahren umgesetzt."
EXAMPLES = [["Bitte geben Sie in einer Kurzbeschreibung den wesentlichen Inhalt des Projektes wieder ", "Khuska Purispa dient der Unternehmertumsförderung und Empowerment von Frauen. Das Projekt baut auf den Erfolgen eines vergangenen von ALTERNAID ermöglichten Projekts auf: 5.271 Tarabäumen wurden gepflanzt. 183 Familien sind auf dem Wege, sich dank neuer unternehmerischer Tätigkeit ein zusätzliches Einkommen aufzubauen. Doch noch ist die Rollen- und Chancenungleichheit hoch im bolivianischen Hochland. Empowerment von Frauen soll im neuen Projekt auf fundamentaler Ebene adressiert werden, mitunter durch ein Female Leadership Programm. Es werden Evaluierungsmethoden entwickelt, um unsere Wirkung im Zusammenhang mit diesem Kernziel messbarer erfassen – unterstützt durch eine von Ehrenamtlichen eigens entwickelte App. Ein breites und diversifiziertes Angebot an Maßnahmen zur Unternehmertumsförderung wird geschaffen, mit der Zielsetzung insgesamt. Maßnahmen zur Unternehmertumsförderung wird geschaffen, mit der Zielsetzung insgesamt 250 Familien Micanis zu zusätzlichen Einkommensquellen zu verhelfen. Das Projekt wird über einen Zeitraum von 3 Jahren umgesetzt."],
            ]

